site_name: Xindmap
site_author: Thomas Petiteau
site_description: Xindmap documentation
repo_url: https://github.com/XanX3601/xindmap

theme:
  name: material

nav:
  - Home: "index.md"
  - References:
    - xindmap: "references/xindmap.md"
    - xindmap.app: "references/xindmap.app.md"
    - xindmap.app.XindmapApp: "references/xindmap.app.XindmapApp.md"
    - xindmap.main: "references/xindmap.main.md"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
            - url: https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
