site_name: Xindmap
site_author: Thomas Petiteau
site_description: Xindmap documentation
repo_url: https://github.com/XanX3601/xindmap

theme:
  name: mkdocs


nav:
  - Home: "index.md"

plugins:
  - search
  - autorefs
  - mkdocstrings
