def compute_round_rectangle_points(x0, y0, x1, y1, radius):
    return (
        x0 + radius,
        y0,
        x0 + radius,
        y0,
        x1 - radius,
        y0,
        x1 - radius,
        y0,
        x1,
        y0,
        x1,
        y0 + radius,
        x1,
        y0 + radius,
        x1,
        y1 - radius,
        x1,
        y1 - radius,
        x1,
        y1,
        x1 - radius,
        y1,
        x1 - radius,
        y1,
        x0 + radius,
        y1,
        x0 + radius,
        y1,
        x0,
        y1,
        x0,
        y1 - radius,
        x0,
        y1 - radius,
        x0,
        y0 + radius,
        x0,
        y0 + radius,
        x0,
        y0,
    )
